server:
  port: 8080
  servlet:
    context-path: /movieTheaterManagement

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.zpjvpfkwbcnszfzdwynf
    password: 3kSE347@123

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
